name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v4

    # 2. Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    # 3. Install dependencies
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Lint the code with ruff
    - name: Lint Code
      run: |
        pip install ruff
        ruff check .

    # 5. Run tests (placeholder for now)
    - name: Run Tests
      run: |
        echo "Tests go here!"
