name: Build, Push, and Deploy with Terraform

on:
  workflow_dispatch:

jobs:
  build-push:
    name: Build and Push Docker Image to GAR
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set Up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure Docker to Use GAR
      run: |
        gcloud auth configure-docker australia-southeast2-docker.pkg.dev

    - name: Build and Push Docker Image
      run: |
        IMAGE="australia-southeast2-docker.pkg.dev/rng-poke-app/poke-app-repo/poke-app:latest"
        echo "IMAGE=$IMAGE" >> $GITHUB_ENV
        docker build -t $IMAGE .
        docker push $IMAGE

  deploy:
    name: Deploy with Terraform
    runs-on: ubuntu-latest
    needs: build-push

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.10.3

    - name: Authenticate with GCP
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}

    - name: Set Up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var="image=$IMAGE" -out=tfplan

    - name: Terraform Apply
      run: terraform apply -input=false tfplan
